name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Show Node.js version
        run: node -v
      - name: Show npm version
        run: npm -v
      - name: Install dependencies
        run: npm install --verbose
      - name: Build React app
        env:
          REACT_APP_API_URL: https://digitalliberia.com
        run: npm run build --verbose

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
